use_frameworks!

platform :ios, '13.0'

target 'AlphaWalletFoundation_Example' do
  pod 'KeychainSwift', :git=>'https://github.com/AlphaWallet/keychain-swift.git', :commit=> 'b797d40a9d08ec509db4335140cf2259b226e6a2'
  pod 'AlphaWalletWeb3Provider', :git=>'https://github.com/AlphaWallet/AlphaWallet-web3-provider', :commit => '9a4496d02b7ddb2f6307fd0510d8d7c9fcef9870'
  pod 'TrustKeystore', :git => 'https://github.com/AlphaWallet/latest-keystore-snapshot', :commit => 'c0bdc4f6ffc117b103e19d17b83109d4f5a0e764'
  pod 'web3swift', :git => 'https://github.com/AlphaWallet/web3swift.git', :commit=> '6d7c01af26bcb75d8a02b6709b089e02ed99af98'
  pod 'SAMKeychain'
  pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna.git', :commit => '06a04bc28783ccbb40efba355dee845a024033e8'
  pod 'TrustWalletCore', '2.6.34'
  pod 'EthereumABI', :git => 'https://github.com/AlphaWallet/EthereumABI.git', :commit => '877b77e8e7cbc54ab0712d509b74fec21b79d1bb'

  pod 'AlphaWalletFoundation', :path => '../'
  pod 'AlphaWalletAddress', :path => '../'
  pod 'AlphaWalletCore', :path => '../'
  pod 'AlphaWalletGoBack', :path => '../'
  pod 'AlphaWalletENS', :path => '../'
  pod 'AlphaWalletOpenSea', :path => '../'

  target 'AlphaWalletFoundation_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0';
    end

    target.build_configurations
      .filter {|e| e.debug?}
      .each do |config|
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
  end
end
