use_frameworks!

platform :ios, '10.0'

target 'AlphaWalletFoundation_Example' do
  pod 'AlphaWalletFoundation', :path => '../'

  target 'AlphaWalletFoundation_Tests' do
    inherit! :search_paths

    
  end
end
